### ISSUE TITLE
Update Binary Ninja API submodule to 3.0 stable

### ISSUE THREAD

**Issue by jonpalmisc** [jonpalmisc/ObjectiveNinja#26]

**Comment by brinlyau** [comment]
https://github.com/jonpalmisc/ObjectiveNinja/blob/master/README.md?plain=1#L48 might wanna change this note too :)

**Comment by jonpalmisc** [comment]
Good call @brinlyau — I'll make sure that gets included as I work on #31 https://github.com/jonpalmisc/ObjectiveNinja/tree/better-readme
