### ISSUE TITLE
ObjectiveNinja crashes on any of the Apple Private Framework dylibs

### ISSUE THREAD

**Issue by cr7pt0pl4gu3** [jonpalmisc/ObjectiveNinja#44]
ObjectiveNinja crashes (workflow or "analyse structures" from plugin menu) when one of the Apple Private Framework dylibs is loaded. Attaching some example files that trigger a crash:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/43863412/165771982-91a11611-9409-4de7-af83-1d28441027db.png">
[binaries.zip](https://github.com/jonpalmisc/ObjectiveNinja/files/8583477/binaries.zip)

**Comment by jonpalmisc** [comment]
Looks like all of these begin crashing in `SelectorAnalyzer`, due to bad pointer decoding from `arp`. Need to investigate more, but leaving this comment as a note to myself.

**Comment by cxnder** [comment]
From glancing at the images / selref lists, it looks like these are libraries extracted from a DSC using something similar to XCode's default extractor. Correct me if i'm wrong there.

This extractor destroys a ton of objc runtime data and leaves a lot of information, making it more difficult to perform RE and near impossible to pull objc runtime info out of. The reason you can still see objc method names is that those are encoded within symbols, not the objc runtime itself.

At the current moment (hopefully changing soon!) there are no good extractors for MacOS :/

Some alternatives you can use to work on in the meantime:
I have a *properly* extracted version of the iOS binary for vCard.framework here: https://headers.cynder.me/index.php?sdk=ios/15.0&fw=/PrivateFrameworks/vCard.framework . rest are also on that site.

DyldExtractor was the tool used there and can be used on all of the iOS shared caches.

You can also work on the ios simulator runtime binaries.
